Control characters are causing issues, if we found them, repr(them)
Fixes:
ValueError: All strings must be XML compatible:
    Unicode or ASCII, no NULL bytes or control characters